---

- name: "Build configuration for access devices"
  hosts: access
  connection: local
  gather_facts: false

  roles:
    - directory_creation
    - baseline
    - aaa
    - ntp
    - logging
    - l3_interfaces
    - enabling_services
    - line_config
    - generate_configs
