---

- name: "Build configuration for access devices"
  hosts: access
  connection: local
  gather_facts: false

  roles:
    - directory_creation
    - baseline
    - ntp
    - syslog
    - l3_interfaces
    - generate_configs
