---

- name: "Napalm testing"
  hosts: testDevices
  # connection: local
  connection: "{{ ansible_connection }}"
  gather_facts: no
  vars:
    - ipv4_addr: 192.168.0.17
    - netmask: 28
    - full_ip: "{{ ipv4_addr }}/{{ netmask }}"

  tasks:
    - name: l3 interfaces
      include_role:
        name: l3_interfaces
    # - name: testing
    #   debug:
    #     msg: "{{ lookup('dict', item) }}"
    #   with_items:
    #     - "{{ Interfaces }}"

  # roles:
  #   - compliance_validation
