---

- name: "Napalm testing"
  hosts: R1
  connection: local
  # connection: "{{ ansible_connection }}"
  gather_facts: no
  vars:
    test_empty_list: ['test':'1']
    test_list:
      - test_item1: "1"
    test_item2: {'test_item2': '2'}
    test_item2_items: "{{ test_item2 | dict2items }}"
    test_item2_key: "{{ test_item2_items[0].key }}"
    test_item2_value: "{{ test_item2_items[0].value }}"

  tasks:
    - name: Debug
      debug:
        msg: "{{ test_empty_list }}"

    - name: Append to list
      set_fact:
        test_empty_list: "{{ test_empty_list + [ { test_item2_key: test_item2_value } ] }}"

    - name: Debug
      debug:
        msg: "{{ test_empty_list }}"

    - name: Debug
      debug:
        msg: "{{ test_empty_list[1] }}"

  # roles:
  #   - compliance_validation
