---

- name: "Genie test"
  hosts: testDevices
  connection: "{{ ansible_connection }}"
  gather_facts: no
  vars:
    genie_parse_command: "show ip interface brief"

  tasks:
  - name: Read in parse_genie role
    include_role:
      name: clay584.parse_genie

  - name: Retrieve interface information
    ios_command:
      commands:
        - "{{ genie_parse_command }}"
    register: output

  - name: Set facts for Genie Filter
    set_fact:
      interfaces: "{{ output['stdout'][0] | parse_genie(command=genie_parse_command, os=ansible_network_os) }}"

  - name: Debug
    debug:
      msg: "{{ interfaces['interface']['FastEthernet0/0']['status'] }}"
