---

- name: "Napalm testing"
  hosts: testDevices
  connection: "{{ ansible_connection }}"
  gather_facts: no

  tasks:

    # - name: get facts from device
    #   napalm_get_facts:
    #     provider: "{{ napalm }}"
    #     filter:
    #       - "interfaces"
    #   register: result
    #
    # - name: set interface information
    #   set_fact:
    #     napalm_learned_interfaces: "{{ result.ansible_facts.napalm_interfaces }}"

    # - name: Shutdown non-configured Interfaes
    #   ios_config:
    #     lines:
    #       - "{{ cur_int_values.State }}"
    #     parents: "interface {{ cur_int_name }}"
    #   with_items:
    #     - "{{ hostvars[inventory_hostname]['Interfaces'] }}"
    #   vars:
    #     cur_int: "{{ item | dict2items }}"
    #     cur_int_name: "{{ cur_int[0].key }}"
    #     cur_int_values: "{{ cur_int[0].value }}"
    #     napalm_int_state: "{{ napalm_learned_interfaces[cur_int_name]['is_up'] }}"
    #     expected_int_state: "{{ cur_int[0].value.is_up }}"
    #   when: "napalm_int_state != expected_int_state"

    - name: "Applying config to {{ inventory_hostname }}"
      ios_config:
        lines:
          - "ntp server {{ item }}"
        save_when: modified
      with_items:
        - "{{ global.ntpserver }}"
