---

- name: "Napalm testing"
  hosts: testDevices
  connection: "{{ ansible_connection }}"
  gather_facts: no

  tasks:
    - name: Install config on device
      napalm_install_config:
        provider: "{{ napalm }}"
        commit_changes: TRUE
        replace_config: TRUE
        config_file: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}/running_config.conf"
        diff_file: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}/diff"
        optional_args: {'global_delay_factor': 2}
    # - name: get facts from device
    #   napalm_get_facts:
    #     provider: "{{ napalm }}"
    #     filter:
    #       - "interfaces_ip"
    #   register: result
    #
    # - name: Print out gathered gather facts
    #   debug:
    #     msg: "{{ result }}"

    # - name: Generate validation report
    #   napalm_validate:
    #     provider: "{{ napalm }}"
    #     validation_file: "./validation/{{ inventory_hostname }}/validate.yaml"
    #   register: validation
    #
    # - name: Print compliance report
    #   debug:
    #     msg: "{{ validation }}"
