---
# tasks file for baseline

- name: Generates required commands at beginning of running_config
  template:
    src: "{{ ansible_network_os }}_baseline.j2"
    dest: "./staging/{{ inventory_hostname }}/000_baseline.cfg"
- name: Generates required commands at end of running_config
  template:
    src: "{{ ansible_network_os }}_baseline_EOF.j2"
    dest: "./staging/{{ inventory_hostname }}/999_baseline_EOF.cfg"
