---

- name: Download latest Vagrant version into /usr/local/bin
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    mode: 0755
