- name: Filter out latest Vagrant version
  shell: set -o pipefail && curl https://releases.hashicorp.com/vagrant/ | grep -o "/[0-9]\..*.[0-9]/" | grep -o "[0-9]\..*.[0-9]" | head -1
  register: result
  changed_when: false
  args:
    warn: false

- name: Set vagrant version fact
  set_fact:
    vagrant_version: "{{ result.stdout }}"

- include: "{{ ansible_distribution }}-install.yml"
