- name: Filter out latest Vagrant version
  shell: curl https://releases.hashicorp.com/vagrant/ | grep href | grep -v '\.\.' | head -1 | grep -o "/[0-9]\..*.[0-9]/" | grep -o "[0-9]\..*.[0-9]"
  register: result
  args:
    warn: false

- name: Set vagrant version fact
  set_fact:
    vagrant_version: "{{ result.stdout }}"

- include: "{{ ansible_distribution }}-install.yml"
