---

- name: Create mount directories
  become: True
  file:
    path: "{{ item.value }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_dict: "{{ fstab_mount_dirs }}"
  loop_control:
    label: "{{ item.value }}"

- name: Generate SMB credential file
  template:
    src: smbcredentials.j2
    dest: "{{ ansible_env.HOME }}/.smbcredentials"
    mode: 0600

- name: Generate fstab-EOF content
  template:
    src: fstab-EOF.j2
    dest: "{{ role_path }}/files/fstab-EOF"
    mode: 0644

- name: Inserting EOF in /etc/fstab
  become: True
  blockinfile:
    path: "/etc/fstab"
    block: "{{ lookup('file', 'fstab-EOF') }}"
    marker: "### {mark} /etc/fstab EOF ###"

- name: Remove the generated fstab-EOF file
  file:
    path: "{{ role_path }}/files/fstab-EOF"
    state: absent
