- name: Ensure samba is installed
  include_role:
    name: install-system-packages
  vars:
    packages_to_install:
      - samba

- name: Create smb.conf template
  template:
    src: smb.j2
    dest: "{{ role_path }}/files/smb.conf"

- name: Copy custom smb.conf and replace existing system version
  become: true
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    mode: '0644'
    backup: yes
    validate: testparm %s

- name: Clear smb.conf template
  file:
    path: "{{ role_path }}/files/smb.conf"
    state: absent

- name: Verify samba share folders exist
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ samba_share_folders }}"
  when: "not samba_share_folders"

- name: Restart samba fileshare services
  become: true
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - smb.service
    - nmb.service
