---

- name: Baseline setup
  hosts: localhost
  become: false
  connection: local
  gather_facts: true

  roles:
    - create-directories
    - install-system-packages
    - install-pip-packages
    - install-docker-ce
