---

- name: Baseline setup
  hosts: all
  ### Executing locally for testing
  # hosts: localhost
  # connection: local
  gather_facts: true

  roles:
    - create-directories
    - install-system-packages
    - configure-host-file
    - install-snap-packages
    - install-pip-packages
    - install-docker-ce
    - create-symlinks
    - update-homeConfig-files
