---

- name: Testing
  hosts: all
  ### Executing locally for testing
  # hosts: localhost
  # connection: local
  gather_facts: true

  roles:
    - install-system-packages
    - install-pip-packages
    - create-directories
