---

# Ansible vault pass: abcd1234

# Need to specify which python to use, otherwise, uses the one found in /usr/bin
ansible_python_interpreter: "{{ lookup('env','HOME') }}/automation/venv/bin/python3"

# Config backup
network_backup_repository: "{{ vault.network_backup_repository }}"
network_backup_dir: "{{ playbook_dir }}/backups"
network_backup_file: "{{ network_backup_dir }}/{{ inventory_hostname }}.cfg"
git_name: "{{ vault.git_name }}"
git_email: "{{ vault.git_email }}"

# Variables as part of the network_cli connection type
ansible_connection: network_cli
ansible_network_os: ios
ansible_user: "{{ vault.username }}"
ansible_password: "{{ vault.adminpass }}"

napalm:
  hostname: "{{ inventory_hostname }}"
  username: "{{ global.username }}"
  password: "{{ global.adminpass }}"
  dev_os: "{{ ansible_network_os }}"

global:
  enable: "{{ vault.enable }}"
  username: "{{ vault.username }}"
  adminpass: "{{ vault.adminpass }}"
  domain: "automation.local"
  syslog:
    - 192.168.1.1
    - 192.168.1.2
  ntpserver:
    - 192.168.2.1
    - 192.168.2.2
