---

- name: Ensure tlp is installed
  include_role:
    name: install-system-packages
  vars:
    packages_to_install:
      - tlp

- name: Start tlp service
  become: true
  service:
    name: "tlp"
    enabled: yes
    state: started

- name: Copy custom tlp configuration file to /etc/tlp.d
  become: true
  copy:
    src: "{{ ansible_product_version }}/10-my-tlp.conf"
    dest: /etc/tlp.d
    mode: '0644'
  notify: Enable TLP
