automation_git_repos:
  - repo: https://github.com/chuanguyen/Ansible-Testing.git
    dest: "{{ ansible_env.HOME }}/automation"
  - repo: https://github.com/chuanguyen/Python-Projects.git
    dest: "{{ ansible_env.HOME }}/automation"
  - repo: https://github.com/chuanguyen/GNS3-My-Projects.git
    dest: "{{ ansible_env.HOME }}/GNS3/projects/GNS3-My-Projects"
