---

- name: Ensure pip requirements are installed
  include_role:
    name: install-system-packages
  vars:
    packages_to_install:
      - python-pip
      - python-setuptools
      - python-virtualenv

- name: Install required pip packages into virtualenv
  pip:
    name: "{{ automation_pip_packages }}"
    virtualenv: "{{ ansible_env.HOME }}/automation/venv"
