---

# Ansible vault pass: abcd1234

ansible_connection: network_cli
ansible_network_os: ios
ansible_user: "{{ vault.username }}"
ansible_password: "{{ vault.adminpass }}"
genie_os: ios

global:
  hostname: "{{ inventory_hostname }}"
  enable: test
  username: "{{ vault.username }}"
  adminpass: "{{ vault.adminpass }}"
