---

- name: "Genie test"
  hosts: testDevices
  connection: "{{ ansible_connection }}"
  gather_facts: no

  tasks:
    - name: get facts from device
      napalm_get_facts:
        provider: "{{ napalm }}"
        filter:
          - "interfaces"
          - "route_to"
      register: result

    - name: Print out gathered gather facts
      debug:
        msg: "{{ result }}"
