---

- name: "Genie test"
  hosts: testDevices
  connection: "{{ ansible_connection }}"
  gather_facts: no

  tasks:
  - name: Read in parse_genie role
    include_role:
      name: clay584.parse_genie

  - name: Retrieve interface information
    ios_command:
      commands:
        - show ip interface brief
    register: output

  - name: Set facts for Genie Filter
    set_fact:
      interfaces: "{{ output['stdout'][0] | parse_genie(command='show ip interface brief', os=ansible_network_os) }}"

  - name: Debug
    debug:
      msg: "{{ interfaces['interface']['FastEthernet1/0']['status'] }}"
