- name: Retrieve cables for specific device from NetBox
  uri:
    url: "{{ netbox_url }}/api/dcim/cables?device={{ inventory_hostname }}"
    method: GET
    return_content: yes
    body_format: "json"
    headers:
      Authorization: "Token {{ netbox_token }}"
  register: nb_output

- name: Sets fact for device cables
  set_fact:
    nb_cables_device: "{{ nb_output.json.results }}"
