---
# tasks file for accessLayer


- name: "Generate network templates for for access layer switches"
  template:
    src: "access.j2"
    dest: "/home/chua_linux/{{ item.Hostname }}_config.txt"
  with_items:
    - "{{ switches }}"
