---
# tasks file for ios_ntp

- template:
    src: "{{ ansible_network_os }}_ntp.j2"
    dest: "./staging/{{ inventory_hostname }}/{{ inventory_hostname }}_ntp.cfg"
  with_items:
    - "{{ hostvars[inventory_hostname] }}"
