automation_pip_packages:
  - gns3-server
  - gns3-gui

system_users: "{{ vault_system_users }}"

# Family NAS
smb_username: "{{ vault_smb_username }}"
smb_password: "{{ vault_smb_password }}"
smb_domain: "{{ vault_smb_domain }}"
family_nas_hostname: "{{ vault_family_nas_hostname }}"
family_nas_FQDN: "{{ vault_family_nas_FQDN }}"
