---
  
- name: Parse and store network information
  include: loop.yml
  with_dict:
    - "{{ genie_parse_commands }}"
  loop_control:
    loop_var: genie_parse_command

- name: Show parsed data after
  debug:
    msg: "{{ genie_parsed_data }}"
