---
# tasks file for generate_configs

- name: Append templates together to create final baseline configuration file
  assemble:
    src: "{{ playbook_dir }}/staging/{{ inventory_hostname }}/"
    dest: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}/running_config.conf"

- name: Delete Staging Directories
  file:
    path: "{{ playbook_dir }}/staging/{{ inventory_hostname }}/"
    state: absent
