- name: Copy sysctl config to /etc/sysctl.d
  become: true
  copy:
    src: "{{ item }}"
    dest: /etc/sysctl.d
    mode: '0644'
  with_fileglob: "files/*"
  loop_control:
    label: "{{ item | basename }}"
