---

- name: Creates directory for configuration building
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Create Template storage directory within the staging directory
      file:
        path: "./staging/{{ inventory_hostname }}/"
        state: directory

    - name: Create directory for final configuration
      file:
        path: "./complete/{{ inventory_hostname }}/"
        state: directory

- name: "Build configuration for access devices"
  hosts: access
  connection: local
  gather_facts: false

  roles:
    - ios_ntp

- name: Combines configuration files and cleans up staging directories
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Append templates together to create final baseline configuration file
      assemble:
        src: "./staging/{{ inventory_hostname }}/"
        dest: "./complete/{{ inventory_hostname }}_FINAL.cfg"

    - name: Delete Staging Directories
      file:
        path: "./staging/{{ inventory_hostname }}/"
        state: absent
