---

- name: Ensure intel-undervolt is installed
  include_role:
    name: install-system-packages
  vars:
    packages_to_install:
      - intel-undervolt

- name: Loading MSR module at boot to enable tool to undervolt
  become: True
  copy:
    src: undervolt.conf
    dest: /etc/modules-load.d/
    owner: root
    group: root
    mode: 0644

- name: Copy the intel-undervolt configuration file
  become: True
  copy:
    src: "{{ ansible_product_version }}/intel-undervolt.conf"
    dest: /etc/intel-undervolt.conf
    owner: root
    group: root
    mode: 0644

### Only enable service once confirmed stable undervolt
# - name: Enable intel-undervolt service
#   become: True
#   service:
#     name: intel-undervolt
#     state: started
#     enabled: True
