---
# tasks file for directory_creation

- name: Create Template storage directory within the staging directory
  file:
    path: "{{ playbook_dir }}/staging/{{ inventory_hostname }}/"
    state: directory

- name: Create directory for final configuration
  file:
    path: "{{ playbook_dir }}/compiled/{{ inventory_hostname }}"
    state: directory

- name: Create directory for config validation
  file:
    path: "{{ playbook_dir }}/validation/{{ inventory_hostname }}/"
    state: directory
