---
# tasks file for accessLayer

- template:
    src: "{{ baselines.access }}"
    dest: "./staging/{{ inventory_hostname }}/001_{{ inventory_hostname }}_access.cfg"
  with_items:
    - "{{ hostvars[inventory_hostname] }}"
