- name: Verify base folders for repos exist
  file:
    path: "{{ item.base_folder }}"
    state: directory
    mode: 0755
  with_items: "{{ automation_git_repos }}"

- name: Clone my project repos
  git:
    clone: yes
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    recursive: yes
    update: no
  with_items: "{{ automation_git_repos }}"
