---

# vault pass: abcd1234

my_git_repos:
  - https://github.com/netbox-community/netbox-docker.git
  - https://github.com/chuanguyen/Ansible-Testing.git
  - https://github.com/chuanguyen/Python-Projects.git

docker:
  gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
  docker_ce_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"

apt_packages:
  - python3-pip
  - python3-setuptools
  - virtualenv
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

system_pip_packages:
  - napalm-ansible
  - docker-compose
  - pyats[full]
  - tabulate
  - yamllint
  - ansible-lint
