---

docker:
  gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
  docker_ce_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"

system_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - python3-pip
  - python3-setuptools
  - snapd
  - software-properties-common
  - virtualenv
  - xz-utils

system_snap_packages:
  - postman

system_pip_packages:
  - ansible-lint
  - docker-compose
  - napalm-ansible
  - pyats[full]
  - pynetbox
  - tabulate
  - yamllint
